SECRET_KEY_BASE: "02d5d82a3c44978191e7ee5751692b97c64e8abb1ef7405cbdbcb8e6f26a2ecda7375ba716316cfb7e41b29c2f3de049e056d58a8afc88eba3cb09e8804595c6"

AWS_ACCESS_ID: "AKIAZVQY7ZYSA2KCDJZQ"
AWS_ACCESS_SECRET_KEY: "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"
AWS_REGION: "ap-northeast-2"
AWS_S3_END_POINT: "https://s3-ap-northeast-2.amazonaws.com"
DB_NAME: "Premium_backend"
DB_USER_NAME: "admin"
DB_USER_PASSWD: "0000"

KAKAO_CLIENT_ID: dddfee223d24c8d197c5764de547993b